stages:
  - build
  - test
before:
  script:
    - apt-get update
    - apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
test:
  image: node:latest
  stage: test
  script:
    - npm ci
    - npx cypress verify
    - npx cypress run